<!--
  ~ Copyright 2020 Digital Asset (Switzerland) GmbH and/or its affiliates
  ~
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<included>
    <appender name="REWRITE_LOG_LEVEL_SYNC" class="com.digitalasset.canton.logging.RewritingAppender">

        <!-- set to true if we should include the testing message rewriting rules -->
        <testing>${REWRITE_TESTING:-false}</testing>

        <appender-ref ref="STDOUT"/>
        <appender-ref ref="FILE"/>

        <!-- Netty issue with not ignoring streams that have been cancelled
             - https://github.com/grpc/grpc-java/issues/4651
             - https://github.com/netty/netty/pull/9402 -->
        <!-- Set maximum log level of Netty to INFO to suppress spurious warnings and errors -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>io.grpc.netty.NettyServerStream</logger>
            <maxLevel>INFO</maxLevel>
            <exceptionMessage>Stream closed before write could take place</exceptionMessage>
        </rewrite>
        <!-- Suppress NettyServerHandler handler error which can happen on cancelled client connections https://github.com/grpc/grpc-java/issues/4651 -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>io.grpc.netty.NettyServerHandler</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Stream Error</contains>
            <exceptionMessage>Received DATA frame for an unknown stream</exceptionMessage>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>io.grpc.netty.NettyServerHandler</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Stream Error</contains>
            <exceptionMessage>Stream closed before write could take place</exceptionMessage>
        </rewrite>
        <!-- Suppress warnings by Hikari to give Canton the opportunity to resolve the problem by retrying -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.zaxxer.hikari.pool.ProxyConnection</logger>
            <maxLevel>INFO</maxLevel>
            <contains>marked as broken</contains>
        </rewrite>
        <!-- Rewrite materializer log-level, as it is a bit dramatic if upstream closes the connection -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>akka.stream.Materializer</logger>
            <maxLevel>INFO</maxLevel>
            <contains>[completion at client] Upstream failed</contains>
            <exceptionMessage>UNAVAILABLE</exceptionMessage>
        </rewrite>
        <!-- get Ledger-api-server mutable state cache to stop logging benign event as WARN -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.platform.store.cache.StateCache</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Failure in pending cache update for key</contains>
        </rewrite>
        <!-- ledger-api-indexer's append-only schema runs "vacuum analyze" which raises warnings on postgres system tables
        in a couple of tests where migration is not run by a superuser, database or table owner, e.g.:
        DB: skipping "pg_statistic" - only superuser or database owner can vacuum it -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor</logger>
            <maxLevel>INFO</maxLevel>
            <contains>can vacuum it</contains>
        </rewrite>
        <!-- Warnings emitted by caffeine when trying to load an entry for the async cache -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>
                com.github.benmanes.caffeine.cache.LocalAsyncCache
            </logger>
            <contains>Exception thrown during asynchronous load</contains>
            <maxLevel>INFO</maxLevel>
        </rewrite>

        <!-- Parallel indexer on H2-based tests (e.g. DemoExampleIntegrationTest) runs into H2-upsert race:
             - Against H2, you either get: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_5 ON PUBLIC.PACKAGES(PACKAGE_ID) ... MERGE INTO packages USING DUAL on package_id
             - Or: org.h2.jdbc.JdbcBatchUpdateException: Timeout trying to lock table ... MERGE INTO packages USING DUAL on package_id

             The rules should be removed once https://digitalasset.atlassian.net/browse/DPP-562 is done.
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.platform.indexer.RecoveringIndexer</logger>
            <contains>Error while running indexer, restart scheduled</contains>
            <exceptionMessage>MERGE INTO packages USING DUAL on package_id</exceptionMessage>
            <maxLevel>INFO</maxLevel>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.platform.store.appendonlydao.DbDispatcher</logger>
            <contains>INDEX_DB_SQL_NON_TRANSIENT_ERROR</contains>
            <exceptionMessage>MERGE INTO packages USING DUAL on package_id</exceptionMessage>
            <maxLevel>INFO</maxLevel>
        </rewrite>

        <!-- Index-db postgres migration script 114 renames identifiers by appending _old making them exceed the 63 character limit
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor</logger>
            <contains>will be truncated to "participant_events_non_consuming_exercise_</contains>
            <maxLevel>INFO</maxLevel>
        </rewrite>

        <!-- Compatibility warning emitted by flyway -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>org.flywaydb.core.internal.database.base.Database</logger>
            <contains>Flyway upgrade recommended: H2 2.1.210 is newer than this version of Flyway and support has not been tested.</contains>
            <maxLevel>INFO</maxLevel>
        </rewrite>
        <!--
            TESTING REWRITE RULES
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>io.grpc.netty.NettyServerStream</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Exception processing message</contains>
            <exceptionMessage>gRPC message exceeds maximum size</exceptionMessage>
            <testing>true</testing>
        </rewrite>

        <!-- Emitted when trying to connect to the database and Oracle is not ready yet -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.zaxxer.hikari.pool.HikariPool</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Exception during pool initialization</contains>
            <testing>true</testing>
        </rewrite>

        <!-- Expected warnings that are emitted by grpc itself; used for GrpcConnectionErrorsIntegrationTest -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>
                io.grpc.internal.ManagedChannelImpl
            </logger>
            <contains>Failed to resolve name.</contains>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>

        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>io.grpc.internal.SerializingExecutor</logger>
            <exceptionMessage>test exception</exceptionMessage>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.jwt.HMAC256Verifier$</logger>
            <contains>HMAC256 JWT Validator is NOT recommended for production environments</contains>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.ledger.api.auth.AuthServiceJWT$</logger>
            <contains>The Token's Signature resulted invalid when verified using the Algorithm</contains>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.platform.store.FlywayMigrations</logger>
            <contains>Asked to migrate-on-empty-schema</contains>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <!-- Expected errors in negative pruning tests in attempts querying pruned state against append-only schema -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.platform.store.appendonlydao.DbDispatcher</logger>
            <contains>Exception while executing SQL query. Rolled back.</contains>
            <exceptionMessage>pruned offset</exceptionMessage>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>

        <!-- Parallel indexer on Oracle-based conformance tests runs into Oracle-upsert race.
             The problem should only occur when storing packages.
             However, we can't restrict the rule to the packages table, because the error message does not mention the affected table.

             Since the rules are rather broad, it is applied during testing only.

             The rules should be removed once https://digitalasset.atlassian.net/browse/DPP-562 is done.
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.platform.indexer.RecoveringIndexer</logger>
            <contains>Error while running indexer, restart scheduled</contains>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite"> <!-- version for Oracle -->
            <logger>com.daml.platform.store.appendonlydao.DbDispatcher</logger>
            <contains>Processing the request failed due to a non-transient database error: ORA-00001: unique constraint</contains>
            <exceptionMessage>ORA-00001: unique constraint</exceptionMessage>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite"> <!-- version for H2 -->
            <logger>com.daml.platform.store.appendonlydao.DbDispatcher</logger>
            <contains>Processing the request failed due to a non-transient database error: Unique index or primary key violation</contains>
            <exceptionMessage>Unique index or primary key violation</exceptionMessage>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>

        <!-- Some UserManagementServiceIT conformance tests (RaceConditionCreateUsers, RaceConditionGrantRights)
             log some duplicate key violation errors.
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite"> <!-- for Postgres -->
            <logger>com.daml.platform.store.dao.DbDispatcherImpl</logger>
            <contains>Processing the request failed due to a non-transient database error: ERROR: duplicate key value violates unique constraint</contains>
            <exceptionMessage>ERROR: duplicate key value violates unique constraint</exceptionMessage>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite"> <!-- for Oracle -->
            <logger>com.daml.platform.store.dao.DbDispatcherImpl</logger>
            <contains>Processing the request failed due to a non-transient database error: ORA-00001: unique constraint</contains>
            <exceptionMessage>ORA-00001: unique constraint</exceptionMessage>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.digitalasset.canton.integration.tests.LoggingIntegrationTestDefault</logger>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.digitalasset.canton.integration.tests.LoggingIntegrationTestOracle</logger>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.digitalasset.canton.integration.tests.LoggingIntegrationTestPostgres</logger>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>

        <!-- Negative testing of invalid ledger-api jwt token in
             MultipleAuthServicesIntegrationTest: UNAUTHENTICATED(6,0): The command is missing a JWT token
             SecuredApisIntegrationTest: PERMISSION_DENIED(7,0): Claims do not authorize to act as party
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.ledger.api.auth.Authorizer</logger>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>

        <!-- Disable warnings about use of divulged contracts.
             We can remove this rule once we have migrated to disclosence.
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>daml.warnings</logger>
            <contains>Use of divulged contracts is deprecated and incompatible with pruning.</contains>
            <maxLevel>INFO</maxLevel>
            <testing>true</testing>
        </rewrite>

        <!-- TODO(i8846) upstream sequencing actor does throw on shutdown -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.grpc.adapter.RunnableSequencingActor</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Unexpected exception while executing</contains>
            <testing>true</testing>
        </rewrite>

        <!-- TODO(i9172) upstream sequencing actor does throw on shutdown -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>com.daml.platform.apiserver.services.transaction.ApiTransactionService</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Unhandled internal error</contains>
            <exceptionMessage>java.util.concurrent.RejectedExecutionException</exceptionMessage>
            <testing>true</testing>
        </rewrite>

        <!-- Disable warnings about leaked connections for test containers
             See: https://github.com/testcontainers/testcontainers-java/issues/2209
        -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>org.testcontainers.shaded.okhttp3.OkHttpClient</logger>
            <maxLevel>INFO</maxLevel>
            <contains>A connection to http://docker.socket/ was leaked. Did you forget to close a response body?</contains>
            <testing>true</testing>
        </rewrite>

        <!-- Disable warning related to image pulling for testcontainers (data continuity tests) -->
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>🐳 [postgres:11]</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Retrying pull for image: postgres</contains>
            <testing>true</testing>
        </rewrite>
        <rewrite class="com.digitalasset.canton.logging.Rewrite">
            <logger>🐳 [postgres:11]</logger>
            <maxLevel>INFO</maxLevel>
            <contains>Docker image pull has not made progress in</contains>
            <testing>true</testing>
        </rewrite>

    </appender>

    <!-- using an async appender to move rendering and filtering of log messages to background thread -->
    <appender name="REWRITE_LOG_LEVEL" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="REWRITE_LOG_LEVEL_SYNC" />
        <discardingThreshold>0</discardingThreshold>
        <queueSize>1024</queueSize>
        <maxFlushTime>0</maxFlushTime>
    </appender>
    <!-- add a shutdown hook for the async appender -->
    <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook" />

</included>
